language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
bundler_args: --jobs=2
script: CODECLIMATE_REPO_TOKEN=30671829a44a12cdaa579f9b8e05f5fac4f70176dd58b2e8487f51380845f3e9 bundle exec rspec
branches:
  only:
    - master
